### ISSUE TITLE
[ BUG ] Arrow keys keycodes recognised as raw

### ISSUE THREAD

**Issue by BachoSeven** [budlabs/typiskt#17]
Hi, I noticed that when running $0 in `exercise` mode, i.e. with the gtypist exercises, there is a nice way to switch between exercises with either Down/Up or also Left/Right arrow
keys.

However, while this does work sometimes, oftentimes it will print out the **raw** keycodes (only the part after the escape code, so for example `^[[B` for the Down key [in my
terminal] but only `[B` gets printed). I will attach a gif demonstrating the above.
Specifically, I can only reproduce this for the Down and Right keys. Up and Left seem to be working fine.

Uhm now that I think about it more, it could be intentional so that one does not skip over exercises(?)

In any case I don't thin it should be that way, since I might want to go Up/Down through completed exercises...

Let me know what you think about this

EDIT: Yea okay so I think there is an intentional part as I thought, since the bug does not happen when only scrolling through completed exercises... :o

**Comment by BachoSeven** [comment]
![video-200830-2347-41](https://user-images.githubusercontent.com/55460785/91670235-c6ca1c00-eb1b-11ea-81e5-be15cc36ca44.gif)

**Comment by budRich** [comment]
Yes you are correct, i knew about that but didn't bother fix it since it would only affect cheaters ;) . But i am sure i can fix this, i will do that before the next release. Thanks for the issue, also nice gif and rice!

**Comment by BachoSeven** [comment]
Thank you:) it's `st` inside `dwm` with picom-ibhagwan-git as compositor.

**Comment by budRich** [comment]
this is fixed now.
