### ISSUE TITLE
[ Feature Request] Ctrl+w to delete word

### ISSUE THREAD

**Issue by BachoSeven** [budlabs/typiskt#18]
Hi, I don't know if this feature is desirable for you, but sometimes I just write a word entirely wrong and I would like to be able to delete it completely using the standard shell
keybinding `ctrl+w`(^w) to delete the word. This would make the program even more bash-like

Let me know what you think about it!

**Comment by budRich** [comment]
I don't like it in a the context of a touch typing tutor, and it will make it very awkward to calculate WPM.
