### ISSUE TITLE
Simplification of cache placement with $XDG_CACHE_HOME

### ISSUE THREAD

**Issue by BachoSeven** [budlabs/typiskt#19]
Hi, thinking about the Freedesktop XDG specifications, I think it would be easier to set typiskt's cache dir at `$XDG_CACHE_HOME/typiskt`, and have that default to `~/.cache/typiskt` if `XDG_CACHE_HOME` is unset, so that you don't need to have the `cache-dir` option nor `TYPISKT_CACHE` variable, since the user can control the cache folder through the aforementioned XDG variable. I think it's more elegant this way

**Comment by budRich** [comment]
Very good idea. And it's a oneline fix for me. I will include that in the next version. Thank you! What's your WPM?

**Comment by BachoSeven** [comment]
It was around 40 before I started using your program; now it's ~75:)

**Comment by budRich** [comment]
finally did this.
