### ISSUE TITLE
[Feature request] Ctrl+h as an alternative to Backspace

### ISSUE THREAD

**Issue by usaoc** [budlabs/typiskt#20]
I'm very used to pressing `Ctrl+h` to delete a character backwards. My mind boggles when I realize that I need to press `Backspace` instead of `Ctrl+h`. Would you mind adding support to `Ctrl+h`? Thanks.

**Comment by budRich** [comment]
Ctrl+h, is that emacs defaults? sounds comfy, backspace key is kind of awkward to reach, I could see myself using that. I will look into how to add it to typiskt, i don't think it is a big deal.

**Comment by usaoc** [comment]
Actually `vi` insert mode default as well! Unlike most people, I always use my palm to press `Ctrl`, so it does feel super comfy ;)

**Comment by budRich** [comment]
this is fixed
