### ISSUE TITLE
[Feature request] Detailed statistics / export

### ISSUE THREAD

**Issue by rixx** [budlabs/typiskt#23]
It would be great to see which words/letters were a cause for typos.

As an alternative (or an additional feature request), it would be great to see these stats over time, or to pass a flag to print them to stdout after you're done (or to a file). I'd like to see if I improve over time, if I have bad days, etc.

**Comment by budRich** [comment]
I added support for `--details` option, if set. details will be written to a file in `TYPISKT_CACHE/details`. Each test will have its own file named with a EPOCHSECONDS time stamp. Below is an example:  

``` text
difficulty=0
score=8803
wpm=90.00
acc=96.700
clicksum=30
badclicks=1
time=4
keys=y:e,:y,s:x,s:e,l:l,d:o,:d,u:e,r:r,a:b,o:o,m:m,p:p,a:a,n:n,y:y
words=company:Company
corpus=/home/bud/git/lab/typiskt/config/wordlists/english-advanced
```

The "keys" and "words" work like this: expected_word/char:typed_word/char .

**Comment by rixx** [comment]
That looks really good, thank you!
