### ISSUE TITLE
Depends on bc

### ISSUE THREAD

**Issue by kattjevfel** [budlabs/typiskt#5]
I got `/usr/bin/typiskt: line 603: bc: command not found` when finishing the test and got a whoppin' 0.00 WPM.

This is not required by anything else on my system so I wouldn't call this "have no dependencies".

**Comment by budRich** [comment]
Ah, yes, i use bc, forgot about that. I think it is necessary with a calculator that can do floating point numbers, but maybe i should use `awk` for this instead, since it is a more common package.

**Comment by budRich** [comment]
it's fixed now. also updated the AUR package.
